# Generated by Django 3.2.23 on 2023-11-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20231111_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.TextField(max_length=100)),
                ('start_time_local', models.TextField(max_length=100)),
                ('end_time_local', models.TextField(max_length=100)),
                ('day', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Store_Details',
            new_name='bq_results',
        ),
    ]
