# Generated by Django 3.2.23 on 2023-11-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231111_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='menu_hours',
        ),
    ]
