# Generated by Django 3.2.23 on 2023-11-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_menu_hours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu_hours',
            new_name='menuhours',
        ),
    ]
