# Generated by Django 3.2.23 on 2023-11-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_menu_hours_menuhours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menuhours',
            new_name='menu_hours',
        ),
    ]
