# Generated by Django 3.2.23 on 2023-11-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_menu_hours_menuhours'),
    ]

    operations = [
        migrations.CreateModel(
            name='store_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.TextField(max_length=100)),
                ('status', models.TextField(max_length=100)),
                ('timestamp_utc', models.TextField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='menuhours',
            new_name='menu_hours',
        ),
    ]
