# Generated by Django 3.2.23 on 2023-11-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20231111_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedStoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.TextField(max_length=100)),
                ('timestamp_utc', models.TextField(max_length=100)),
                ('day', models.IntegerField()),
                ('start_time_local_1', models.TextField(max_length=100)),
                ('end_time_local_1', models.TextField(max_length=100)),
                ('start_time_local_2', models.TextField(max_length=100)),
                ('end_time_local_2', models.TextField(max_length=100)),
            ],
        ),
    ]
