# Generated by Django 3.2.23 on 2023-11-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_aggregatedstoreinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aggregatedstoreinfo',
            old_name='timestamp_utc',
            new_name='timeszone_str',
        ),
    ]
