# Generated by Django 3.2.23 on 2023-11-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_timestamp_utc_aggregatedstoreinfo_timeszone_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='timestamp_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.TextField(max_length=100)),
                ('status', models.TextField(max_length=100)),
                ('timestamp_utc', models.TextField(max_length=100)),
                ('day', models.IntegerField()),
            ],
        ),
    ]
