# Generated by Django 3.2.23 on 2023-11-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_timestamp_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp_day',
            name='day',
            field=models.IntegerField(default=-1),
        ),
    ]
